### ISSUE TITLE
Edge driver under headless mode causing page crash on some specified URLs

### ISSUE THREAD

**Issue by mingl0280** [MicrosoftEdge/EdgeWebDriver#5] opened 2022-03-14 05:37 UTC
Selenium: Selenium 4
Platform: C# .Net Core 5 Web Application (Windows x64)
Exception text:
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

OpenQA.Selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless MicrosoftEdge=99.0.1150.39)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.set_Url(String value)
   at OpenQA.Selenium.Navigator.GoToUrl(String url)
   at TestGetSnapshotImage.Startup.GetSnapshotDelegate_MSEdge(HttpContext Context) in H:\VS2017\C#\TestGetSnapshotImage\Startup.cs:line 223
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Code snippet to replicate the issue:
``` C#
        private async Task GetSnapshotDelegate_MSEdge(HttpContext Context)
        {
            var d_driver = DownloadAndUncompressEdgeDriver();
            if (d_driver != "")
            {
                await Context.Response.WriteAsync(d_driver);
                return;
            }

            var options = new EdgeOptions();
            options.AddArgument("headless"); // Remove this line and the Selenium will work properly.
            options.AddArgument("--no-sandbox");
            options.UnhandledPromptBehavior = UnhandledPromptBehavior.Dismiss;
            options.SetLoggingPreference(LogType.Driver, LogLevel.Debug);
            EdgeDriver driver;
            try
            {
                driver = new EdgeDriver(Path.GetDirectoryName(_parentDir + "/edge_driver/"), options);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                await Context.Response.WriteAsync("Error fetching driver!");
                return;
            }
            driver.Manage().Window.Size = new Size(1760, 1080);
            
            var req_url = await new StreamReader(Context.Request.Body).ReadToEndAsync();
            if (req_url.Contains("url="))
            {
                req_url = req_url.Substring("url=".Length);
            }

            if (!req_url.StartsWith("http"))
            {
                req_url = "http://" + req_url;
            }
            driver.Navigate().GoToUrl(req_url); // Crash at here.
            var screen_shot = ((ITakesScreenshot) driver).GetScreenshot();
            driver.Close();
            driver.Quit();
            Context.Response.Headers.Add("Content-Type", "text/plain");
            Context.Response.Headers.Add("Access-Control-Allow-Origin","*");
            Context.Response.Headers.Add("Access-Control-Allow-Methods", "POST");
            await Context.Response.WriteAsync("data:image/png;base64,"+screen_shot.AsBase64EncodedString);
        }
```
POST data body: `url=www.cnn.com`

**Comment by bwalderman** [comment] 2022-03-28 17:07
Hi @mingl0280, can you share a complete sample project that reproduces the bug? I'm not very familiar with ASP.NET so I'm not sure how to get the above snippet running. I tried running just the Selenium parts in a standalone .Net console application with url `http://www.cnn.com` but I was not able to reproduce the crash.

**Comment by bwalderman** [comment] 2022-04-11 17:24
Hi @mingl0280, without more complete repro steps I will need to close this issue. Please feel free to reopen if you would like to provide more details.

**Closed by bwalderman** 2022-04-11 17:24 UTC
Labels: bug, tracked
