### ISSUE TITLE
Crash Browser and Error with ver99 or higher driver and browser

### ISSUE THREAD

**Issue by kotobana** [MicrosoftEdge/EdgeWebDriver#8] opened 2022-03-30 07:59 UTC
Hi team!

When I used Edge browser and EdgeDriver, crash browser many time
This problem has occurred since ver99.

Error log
`org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: MicrosoftEdge=99.0.1150.55)
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'DESKTOP-LA8L9DA', ip: '192.168.0.172', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_322'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [966627ef986ff4dacd81851f6f8091b3, getTitle {}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 99.0.1150.55, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:55636}, msedge: {msedgedriverVersion: 99.0.1150.55 (c8275fcfc2e02..., userDataDir: C:\Users\asirrera\AppData\L...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:55636/devtoo..., se:cdpVersion: 99.0.1150.55, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 966627ef986ff4dacd81851f6f8091b3
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:614)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
        at org.openqa.selenium.remote.RemoteWebDriver.getTitle(RemoteWebDriver.java:333)
        at com.eupho.tool.MainKt.simulatePageTransitionOperation(Main.kt:79)
        at com.eupho.tool.MainKt.execScenario(Main.kt:49)
        at com.eupho.tool.MainKt.main(Main.kt:13)
        at com.eupho.tool.MainKt.main(Main.kt)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.lang.Thread.run(Thread.java:750)`

Specifically, it occurs as follows.
- No problem
Browser 99 -  Driver 98.X.X.X
Browser 99 -  Driver 99.0.1111.0
Browser 99 -  Driver 99.0.1112.0
Browser 99 -  Driver 99.0.1113.0
- Occurred error
Browser 99 -  Driver 99.0.1117.0~
Browser 100-  Driver 99.0.1117.0~
Browser 100-  Driver 100

And occurs when the following conditions are met.
Low spec PC(RAM:4GB,  CPU E3-1270 v6 @ 3.80GHz、3792 Mhz、2 core)  and Have a lot of subframes sites
Share the execution script. 
[bug-reproduction.zip](https://github.com/MicrosoftEdge/EdgeWebDriver/files/8378306/bug-reproduction.zip)

The higher the PC spec, the lower the frequency of occurrence.

Chrome Browser happens same issue.
I am creating an issue but there is no response so please help any idea.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4053

maybe same issue.
https://github.com/MicrosoftEdge/EdgeWebDriver/issues/5

Thank you for your helping.

**Comment by tatsuki-tanabe** [comment] 2022-04-14 06:21
This issue also occurs in the latest version (v102).
I want to rewrite the old source version and build the driver to avoid this problem.
Can I create the msedgedriver myself?

**Comment by bwalderman** [comment] 2022-05-02 19:34
@kotobana Thank you for reporting this issue. I've added it to the team's backlog to investigate. Can you confirm whether this is also occurring in Chrome with ChromeDriver?

@tatsuki-tanabe , the source for msedgedriver is not available, but it is based on Chromium's ChromeDriver which is open-source and available [here](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/chromedriver).

**Comment by kotobana** [comment] 2022-05-06 02:23
Thanks for the response.


>Thank you for reporting this issue. I've added it to the team's backlog to investigate. Can you confirm whether this is also occurring in Chrome with ChromeDriver?

Yes, this problem is also happening with ChromeDriver.
I've already posted this to ChromeDriver's Issue.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4053

>@tatsuki-tanabe , the source for msedgedriver is not available, but it is based on Chromium's ChromeDriver which is open-source and available 

As for testing on Chrome, I have a workaround with our own driver that reverts the commit .
But EdgeDriver can't build it, so it can't remove the problem.
And ChromeDriver does not work with Edge Browser.

**Comment by bwalderman** [comment] 2022-05-06 17:14
@kotobana, can you share details and a diff of the patch you made to ChromeDriver to get it working again? Our team may be able to help get it merged into ChromeDriver and EdgeDriver.

**Comment by kotobana** [comment] 2022-05-10 05:42
@bwalderman san
Thank you for helping!
I share issue details.

Issue
Crashes occur when certain conditions are met with version 100 or higher drivers.
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed

Certain conditions
・Open heavy sites with lots of subframes
 ex. 
    https://kakaku.com/
  Lightweight sites will not occur no matter how low the PC specs are
    
・Low spec PC
   https://azure.microsoft.com/ja-jp/pricing/details/virtual-machines/windows/ 
   B2 spec happens many time.
  Rarely crashes even with high PC specs

Reproduction script (need to java8 and mvn)
[web-automation-bug-reproduction0510.zip](https://github.com/MicrosoftEdge/EdgeWebDriver/files/8657609/web-automation-bug-reproduction0510.zip)
please do unzip and execute exec.bat

Below is a rewritten and built version of the Driver that does not have the error
[chromedriver_fixbug_101.zip](https://github.com/MicrosoftEdge/EdgeWebDriver/files/8657621/chromedriver_fixbug_101.zip)

We have investigated and found that this is occurring after the following commit.
However, it was not possible to determine the cause of the problem in any further detail.
https://chromium.googlesource.com/chromium/src/+/48782ec6182e9584ea66d9d5c30f800dfd3fcdaa

These are our current conditions.
Please let me know if there is any information you need.
Thank you.

**Comment by bwalderman** [comment] 2022-05-23 18:27
Thank you for the extra details. I was able to reproduce the crash and find the root cause. This may already be fixed in Chromium with https://source.chromium.org/chromium/chromium/src/+/481b75fc3dc00cedaa3f09403ffd67c29f080447

That fix is available in Edge/Edge WebDriver Canary 103.0.1263.0. Please try with that version and see if the crash is fixed.

**Comment by kotobana** [comment] 2022-05-30 04:26
Thank you for response.

I tested on 103.0.1263.0.
However, I got the following crashed error when same time.
Because of this error I cannot determine if the previous problem has been corrected or if it is the same problem.

`org.openqa.selenium.WebDriverException: unknown error: unexpected command response
  (Session info: MicrosoftEdge=103.0.1264.2)
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'DESKTOP-C0GTV41', ip: '192.168.0.148', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [a341893c8876a4817fb3736cc47aa0b6, clickElement {id=6fb41cad-c9b7-47b1-b82f-6dd41b04f5cc}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 103.0.1264.2, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:62430}, msedge: {msedgedriverVersion: 103.0.1264.2 (96084fa376f76..., userDataDir: C:\Users\tanabe\AppData\Loc...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62430/devtoo..., se:cdpVersion: 103.0.1264.2, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: msedge on WINDOWS (a341893c8876a4817fb3736cc47aa0b6)] -> css selector: .p-result_list .p-item_name]
Session ID: a341893c8876a4817fb3736cc47aa0b6
org.openqa.selenium.WebDriverException: unknown error: unexpected command response
  (Session info: MicrosoftEdge=103.0.1264.2)
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'DESKTOP-C0GTV41', ip: '192.168.0.148', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [a341893c8876a4817fb3736cc47aa0b6, clickElement {id=6fb41cad-c9b7-47b1-b82f-6dd41b04f5cc}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 103.0.1264.2, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:62430}, msedge: {msedgedriverVersion: 103.0.1264.2 (96084fa376f76..., userDataDir: C:\Users\tanabe\AppData\Loc...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62430/devtoo..., se:cdpVersion: 103.0.1264.2, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: msedge on WINDOWS (a341893c8876a4817fb3736cc47aa0b6)] -> css selector: .p-result_list .p-item_name]
Session ID: a341893c8876a4817fb3736cc47aa0b6
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:251)
        at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
        at com.eupho.tool.MainKt.execScenario(Main.kt:49)
        at com.eupho.tool.MainKt.main(Main.kt:13)
        at com.eupho.tool.MainKt.main(Main.kt)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.lang.Thread.run(Thread.java:748)
Closing Driver Connection
===== Scenario End =====`

**Comment by kotobana** [comment] 2022-06-01 07:23
Hi @bwalderman san,
 I tested latest(today's update version) Chromium and ChromeDriver(104.0.5096.0)
"session deleted because of page crash from unknown error"  and "unexpected command response" did not occur and ended normally.
Thank you for many helping!!

It would be very helpful if this correction could be applied to ver103 as well...!
Thank you.

**Comment by bwalderman** [comment] 2022-06-23 17:10
The ChromeDriver owners have requested to merge this fix into 103. You can track the progress at https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121. I am going to close this issue. Please feel free to reopen if the issue occurs again.

**Closed by bwalderman** 2022-06-23 17:10 UTC
Labels: bug, tracked
