### ISSUE TITLE
EdgeDriver with Selenium Testing WebView 2 - Only ASCIIZ protocol mode is supported 

### ISSUE THREAD

**Issue by philcgbt** [MicrosoftEdge/EdgeWebDriver#122] opened 2023-10-19 15:48 UTC
Hi Guys,

Since version 117 of the edge driver we have been seeing the following error:

“_OpenQA.Selenium.WebDriverException : unknown error: only ASCIIZ protocol mode is supported_”

We have been putting together a large, automated test suite using Selenium to test a react site hosted within a webView and it has been working perfectly until we updated to version 117 of the edge driver. Our company pushes updates of Edge and the Edge WebView2 Runtime to all users at the same time thus we need to ensure that our test suite is kept inline with this update cycle and have no choice about the version that we use.

The error is not limited to version 117 of the edge driver, it seems that there are issues from version 117 onwards. I’ve tested numerous versions of the driver post version 117 to see whether I can resolve the issue, but it seems consistently broken when trying to test a webview. If I test using just a browser then I do not see the issue.

I followed this MS learning doc to prove that the driver works with edge and all the tests were successful - https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp

I also followed the MS learning doc on how to automate tests with edge driver and selenium so our test suite and app were removed from the equation and I see the same ASCIIZ error - https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

I would really appreciate if this issue could be looked into as soon as possible. Please let me know if I can provide any further information.

Cheers,
Phil

**Comment by Nickog13** [comment] 2023-10-20 14:03
Hi,

yes, edgedriver seems to be broken since 117 together with Webview2. There is indeed already this issue, that I have opened a few weeks ago: #116 

However, I am not completely sure whether someone responsible for this repository/edgedriver has already looked into it or even has been made aware of. Can someone responsible please confirm that this is currently in the process of being looked at or at least that someone is aware of the issue?  As this most likely blocks all automations that try to test Webview2 based applications.

Thank you!

**Comment by bwalderman** [comment] 2023-12-15 21:57
Duplicate of #116

**Closed by bwalderman** 2023-12-15 21:57 UTC
Labels: bug
