### ISSUE TITLE
getting Error "session deleted because of page crash" when using the HasAuthentication interface

### ISSUE THREAD

**Issue by reinsch82** [MicrosoftEdge/EdgeWebDriver#55] opened 2022-11-02 10:43 UTC
I'm using the HasAuthentication interface from selenium 4.5.3.
like that:

```
      if (driver instanceof HasAuthentication) {
        var auth = (HasAuthentication)driver;
        auth.register(
          uri -> uri.getHost().contains(m_config.getLoginDomain()),
          UsernameAndPassword.of("user", "password"));
      }
```
This works fine in Chrome but not in Edge.
In Edge I get the mentioned error "session deleted because of page crash" when calling `driver.get("url")`

**Comment by bwalderman** [comment] 2022-11-03 18:01
Hi @reinsch82 , I'm not able to reproduce the issue. I tried with this sample:

```java
import org.openqa.selenium.HasAuthentication;
import org.openqa.selenium.UsernameAndPassword;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;

public class EdgeDriverTest {
    public static void main(String[] args) throws InterruptedException {
        EdgeDriver driver = new EdgeDriver();

        if (driver instanceof HasAuthentication) {
            var auth = (HasAuthentication)driver;
            auth.register(
                    uri -> uri.getHost().contains("httpbin.org"),
                    UsernameAndPassword.of("user", "password"));
        }

        driver.navigate().to("http://httpbin.org/basic-auth/user/password");

        Thread.sleep(5000);

        driver.quit();
    }
}
```

Can you share which Edge browser and driver version you are using?

**Comment by bwalderman** [comment] 2022-12-14 18:42
Closing since there hasn't been any response.

**Closed by bwalderman** 2022-12-14 18:42 UTC
Labels: bug

**Comment by reinsch82** [comment] 2022-12-14 19:20
@bwalderman appreciate your quick response, sorry for missing it.
I'm now at another job and hence the repro is not so easy anymore.
