### ISSUE TITLE
Starting Microsoft Edge WebDriver 112.0.1722.39

### ISSUE THREAD

**Issue by Sowmya2586** [MicrosoftEdge/EdgeWebDriver#81] opened 2023-04-14 00:46 UTC
I cant able to create a microsoft edge new version

**Comment by bwalderman** [comment] 2023-04-14 04:54
Hi @Sowmya2586 , can you share more information:
- Selenium version
- Sample code

**Comment by mbtlab** [comment] 2023-04-16 14:19
I have the same question:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate []: Constructor threw exception
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:223) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1300) ~[spring-beans-6.0.6.jar:6.0.6]
	... 49 common frames omitted
Caused by: org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:56236/devtools/browser/f580794a-2901-4d9a-8dd4-6b6b74c1946a



<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.8.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>3.141.59</version>
        </dependency>

**Comment by mbtlab** [comment] 2023-04-16 14:28
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: EdgeDriver
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:107) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:116) ~[selenium-chromium-driver-4.5.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114) ~[selenium-chromium-driver-4.5.3.jar:na]
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:54) ~[selenium-edge-driver-4.5.3.jar:na]
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:46) ~[selenium-edge-driver-4.5.3.jar:na]
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:42) ~[selenium-edge-driver-4.5.3.jar:na]
	at com.mbtlab.liveJob.service.impl.SimulationLoginServiveImpl.<init>(SimulationLoginServiveImpl.java:42) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:197) ~[spring-beans-6.0.6.jar:6.0.6]
	... 51 common frames omitted

**Comment by bwalderman** [comment] 2023-07-05 15:58
Closing. Not enough info to reproduce.

**Closed by bwalderman** 2023-07-05 15:58 UTC
Labels: bug
