### ISSUE TITLE
Edge Instance started from one user's session moves to another user's session connected to same server

### ISSUE THREAD

**Issue by nc2956** [MicrosoftEdge/EdgeWebDriver#86] opened 2023-05-22 16:14 UTC
Here is the scenario: 
User1, logged into a server, launches MS Edge via the Edge driver.  User1 enters a URL and is taken to that site in that browser.
User2 logged into the same server and launches MS Edge via the Edge driver.  User2 enters the same URL in the browser, and suddenly, that browser disappears from User2's screen and appears on User1's screen.

The Edge driver version in use here is 109.0.1518.61
Microsoft EdgeVersion 109.0.1518.61 (Official build) (64-bit)

[Edge-Driver-Error-Log.txt](https://github.com/MicrosoftEdge/EdgeWebDriver/files/11533511/Edge-Driver-Error-Log.txt)

The driver error log is attached. 

AB#44840120

**Comment by bwalderman** [comment] 2023-05-30 19:08
Thank you for reporting this. I've added it to our internal backlog for investigation.

If possible, can you share some sample code to reproduce the issue and specifically the EdgeOptions you are using for User1 and User2?

**Comment by bwalderman** [comment] 2023-12-08 07:45
Closing as not able to reproduce without further information about the environment and code that resulted in the error.

**Closed by bwalderman** 2023-12-08 07:45 UTC
Labels: bug, tracked
