### ISSUE TITLE
EdgeDriver Version 117.0.2045.31 - only ASCIIZ protocol mode is supported error

### ISSUE THREAD

**Issue by Nickog13** [MicrosoftEdge/EdgeWebDriver#116] opened 2023-09-19 15:22 UTC
Hi All,

before describing the issue I would like to emphasize that everything has been fine with EdgeDriver Version 112, 114, 115.
My setup is as follows: I have an application based upon Tauri, that I would like to automatically test via Selenium. Therefore Tauri offers a Webdriver server interface ([tauri-driver](https://lib.rs/crates/tauri-driver)) in between the application and the webdriver. As I mentioned with earlier EdgeDriver versions this worked totally fine. I create the selenium webdriver instance with 

await new Builder()
        .withCapabilities(capabilities)
        .usingServer(serverURL)
        .build());
        

Here it fails since 117 with the error message "_WebDriverError: unknown error: only ASCIIZ protocol mode is supported_"

Thank you and best regards
Dominik

**Comment by jbakeri4** [comment] 2023-09-19 17:18
I'm not familiar with Tauri, but you mentioned its driver worked up until EdgeDriver version **115**- what about 116?

**Comment by Nickog13** [comment] 2023-09-19 19:08
Hi,

I have tried 116 but together with MsEdge version 117 installed (edge updates are controlled by corporate IT). With 116 I got another error "DevToolsActivePort file doesn't exist", but I have not further looked into it due to the version mismatch between edgedriver and installed edge version on the machine.

**Comment by jbakeri4** [comment] 2023-09-19 19:20
Could you download a v.116 binary, point your WebDriver to it to see if it works with that version?

Regarding the DevToolsActivePort, there have been many posts on StackOverflow about it. Try adding the [`"--disable-dev-shm-usage"` argument to EdgeOptions](https://stackoverflow.com/questions/70825917/selenium-common-exceptions-webdriverexception-message-unknown-error-devtoolsa), that worked for me.

**Comment by Nickog13** [comment] 2023-09-20 09:07
The problem here is, the tauri app automatically fetches functionality (WebView2) from the installed Edge version at startup, so I cannot manually change the edge version in a simple way (would need to only have 116 installed). Further, as far as I know, it is not possible to specify browser arguments to the tauri application (could be wrong here, I will also ask the tauri github for support here)

**Comment by jbakeri4** [comment] 2023-09-20 14:55
Oh, I see. I did not know of the specifics of how Tauri interoperates with Edge. I was thinking you could specify a binary path like with Selenium, for example:

`options.setBinary("C:\\Program Files\\Mozilla Firefox\\firefox.exe");`

Sorry I couldn't be of more help.

**Comment by aleenadavy90** [comment] 2023-09-20 21:45
Hi, I am facing same issue 
https://github.com/SeleniumHQ/selenium/issues/12798

**Comment by n8bits** [comment] 2023-09-26 16:04
> Hi,
> 
> I have tried 116 but together with MsEdge version 117 installed (edge updates are controlled by corporate IT). With 116 I got another error "DevToolsActivePort file doesn't exist", but I have not further looked into it due to the version mismatch between edgedriver and installed edge version on the machine.

Hey, don't know if this will help you, but when I get the "DevToolsActivePort file doesn't exist" error testing our Tauri app I can get around it by running VS Code in non-admin mode. No idea why this works. 

As for the ASCIIZ protocol error, I'm hoping they have a fix for this soon. I can confirm things worked fine in the previous versions of EdgeDriver, but I am now facing the same issue as you.

**Comment by s-simoncelli** [comment] 2023-10-05 13:38
+1

**Comment by Elanis** [comment] 2023-10-14 16:19
Same issue with 118.0.2088.46

**Comment by bwalderman** [comment] 2023-12-15 22:00
This was a bug impacting WebDriver communicate with a WebView2 process. Chromium recently updated WebDriver to communicate with the browser process through anonymous pipes instead of a websocket on all OSes, but the doesn't currently work for WebView2 apps because of the different process architecture.

The bug has been fixed in the latest WebDriver and WebView2 version (120+) by default to websocket communications as before. We're looking into adding pipe support for WebView2 processes in the future. WebView2 automation through WebDriver should "just work" without clients needing to make any changes going forward.

**Closed by bwalderman** 2023-12-15 22:00 UTC
Labels: bug

**Comment by Elanis** [comment] 2023-12-21 18:16
I can confirm my tauri/webdriverio tests are now working. Thanks !
