### ISSUE TITLE
In Microsoft Edge Print Screen is not recognized as Separate Window Handle.

### ISSUE THREAD

**Issue by csharsha** [MicrosoftEdge/EdgeWebDriver#120] opened 2023-10-16 07:44 UTC
Till MS Edge Version 116, Print screen was recognized as separate Window Handles. After the browser was updated to 117 and higher, print screen is no longer recognized as separate window handle and thereby preventing the user to switch to the print window to handle the controls like Print, Cancel or access the print content. But the same scenario is working in chrome version 116 and above. Is this a bug in msedge driver?

**Comment by evanbaule** [comment] 2023-10-17 20:45
Bumping this issue. I have a number of automations that rely on this behavior of a designated window handle for that Print Preview dialog which are inoperable right now as a result of this change. Would appreciate some word on whether or not this is a deliberate change before exploring other options.

**Comment by anitabogner** [comment] 2023-10-25 05:55
I''m facing the same problem and reported an issue dir that here a while ago :(
https://github.com/MicrosoftEdge/EdgeWebDriver/issues/115

**Comment by bwalderman** [comment] 2023-12-15 22:41
Duplicate of #115

**Closed by bwalderman** 2023-12-15 22:41 UTC
Labels: bug
