### ISSUE TITLE
EDGE_IDENTITY: Get Default OS Account failed:

### ISSUE THREAD

**Issue by Phoebian** [MicrosoftEdge/EdgeWebDriver#49] opened 2022-09-30 21:22 UTC
I have a very basic setup, and trying to run a test of the following code based off Microsofts "[Automate Microsoft Edge](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=python#automate-microsoft-edge)" code snippit:

```python
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Edge()

driver.get('https://bing.com')

element = driver.find_element(By.ID, 'sb_form_q')
element.send_keys('WebDriver')
element.submit()

time.sleep(5)
driver.quit()
```

The outcome is correct, Edge opens>goes to Bing>searches for WebDriver>Closes Edge.
But in the terminal I get so many errors, but specifically, I am interested in the 2nd line, "EDGE_IDENTITY: Get Default OS Account failed":

DevTools listening on ws://127.0.0.1:65470/devtools/browser/73be1ada-8666-43a2-888e-b53255f60a1f
**[10536:18144:0930/222000.308:ERROR:edge_auth_errors.cc(415)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string:** 

[10536:18144:0930/222004.153:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
[10536:18144:0930/222005.761:ERROR:device_event_log_impl.cc(214)] [22:20:05.753] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
[10536:18144:0930/222005.762:ERROR:device_event_log_impl.cc(214)] [22:20:05.761] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[10536:18144:0930/222005.762:ERROR:usb_descriptors.cc(141)] Failed to read length for configuration 1.
[10536:18144:0930/222005.762:ERROR:usb_descriptors.cc(100)] Failed to read all configuration descriptors. Expected 2, got 1.
[10536:18144:0930/222005.763:ERROR:device_event_log_impl.cc(214)] [22:20:05.762] USB: usb_device_win.cc:96 Failed to read descriptors from \\?\usb#vid_17ef&pid_a359#301e3dd68#{a5dcbf10-6530-11d2-901f-00c04fb951ed}.
[10536:18144:0930/222005.763:ERROR:device_event_log_impl.cc(214)] [22:20:05.762] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[10536:18144:0930/222005.764:ERROR:device_event_log_impl.cc(214)] [22:20:05.764] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[10536:18144:0930/222005.765:ERROR:device_event_log_impl.cc(214)] [22:20:05.764] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

Is this a bug? Or is the Microsoft code snippet incorrect?
I am worried that with such little code and the amount of errors, It will make troubleshooting harder down the line.

Information:
- Browser: Version 105.0.1343.53 (Official build) (64-bit)
- Selenium: 4.5.0
- Driver: Microsoft Edge WebDriver 105.0.1343.53 x64
- Python: 3.10.7 64-bit
- OS: Windows 10 21H2 19044.2006
- VSCode: 1.71.2

**Comment by bwalderman** [comment] 2022-10-04 18:11
Those error logs are generated by Edge, not msedgedriver. The driver is simply passing Edge's log output through to the console. These are understandably distracting but don't indicate a problem with WebDriver and won't impact the test.

**Comment by bwalderman** [comment] 2022-10-13 17:20
Closing this issue. Some browser features may not work as intended when Edge is running under WebDriver, which causes them to generate error logs. From the WebDriver point of view though, showing log output from the browser is by design.

**Closed by bwalderman** 2022-10-13 17:20 UTC
Labels: bug

**Comment by ceywj** [comment] 2024-01-25 01:59
I encountered the same problem

**Comment by Antimatterr** [comment] 2024-03-23 13:17
In my case it's closing the window completely and automation are failing.

**Comment by warrenbullnz** [comment] 2024-03-26 01:27
I was running into the same problem as you guys and for what it's worth I found a solution.

I went to the "[Automate Microsoft Edge](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=python#automate-microsoft-edge)" and read further down, Manage and Configure Webdriver Service.

I added the following lines to the above example code:

```
from selenium.webdriver.edge.service import Service

service = Service(verbose = True)
```

and replaced 
`driver = webdriver.Edge() `
with 
`driver = webdriver.Edge(service = service)`

I hashed out the time sleep and driver quit at the bottom to see if the browser stays open and it does! 

Hope this helps someone?

**Comment by WingGao** [comment] 2024-06-04 06:53
You need to delete the old msedgedriver.exe file and download the version matches your Edge

**Comment by sdkng44** [comment] 2024-09-03 04:57
> You need to delete the old msedgedriver.exe file and download the version matches your Edge

Updating the webdriver with the lastest version solved my issue.

ISSUE: "EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError"
