### ISSUE TITLE
IWebDriver.WindowHandles in Selenium 4 does not return correct number of open browser windows

### ISSUE THREAD

**Issue by p-system** [MicrosoftEdge/EdgeWebDriver#19] opened 2022-05-02 11:16 UTC
I updated Selenium to 4. I test legacy app that runs only on IE. Now IE will be closed down and I need to switch to MS Egde in capability mode. My tests during execution need to switch to new browser windows and uses function IWebDriver.WindowHandles to do it (code below).

Comparing to Selenium 3 I had to add new options for a driver to run test on Edge like this:

var options = new InternetExplorerOptions();
options.AttachToEdgeChrome = true;
options.EdgeExecutablePath = @"\msedge.exe";

Then I use code like this to switch between browser windows when user open new browser window in tested application:

public Context SwitchToNewIEWindow(string windowTitle, bool isEqual = true)
{
for (int i = 0; i < context.GetTimeout().Seconds; i++)
{
try
{
var ieWindowHandlers = context.GetDriver().WindowHandles;
foreach(var handler in ieWindowHandlers)
{
var window = context.GetDriver().SwitchTo().Window(handler);
bool condition = isEqual ? window.Title == windowTitle : window.Title.Contains(windowTitle);
if (condition)
{
context.SetDriver(window);
context.SetCurrentWindow(windowTitle);
return context;
}
}
}
catch (Exception)
{
context.Wait(1);
}
}
throw new Exception($"No window found with title: {windowTitle}");

    }

In Selenium 3 everything works fine and WindowHandles function returns 2 handles. In Selenium 4 and IEDriver in Edge mode this function returns only 1 handle of main browser window. In my case waiting a few seconds ( as it is recommended in guidelines) does not change anything. Even after a minute I still get only handle of first window. Any suggestions how to make it work properly again in Selenium 4. 

I am aware of issue https://github.com/SeleniumHQ/selenium/issues/8868 but I was redirected here as a correct place to report this issue.

**Comment by bwalderman** [comment] 2022-05-02 19:39
Thank you for reporting this issue. I've added it to the team's backlog to investigate.

**Comment by p-system** [comment] 2022-05-06 12:35
I was able to access the code of the legacy applications I'm testing using Selenium and found that windows opened by the **window.showModelessDialog()** function are detected by IEDriver.WindowHandles, but those windows that are opened by the **window.open(url, name, winParms);** function are not detected and the number of handles remains the same even after waiting a few minutes. I hope it clue will allow You to fix this problem. I have found more people reported this problem on various forums and websites. Please let me know if this is enough information for you.

**Comment by thesrinu** [comment] 2022-05-17 16:23
Do we know if there is any ETA from Microsoft team for a fix on the driver?

**Comment by ramaraju22** [comment] 2022-05-23 08:20
Our application will support only in IE browser but from 15th June onwards IE browser will not work so we have only option to use Edge in IE mode. Due to issue https://github.com/SeleniumHQ/selenium/issues/8868 selenium scripts are not working. It is a road blocker. Could you please provide resolution on priority before 15th June.

**Comment by ramaraju22** [comment] 2022-05-23 08:22
Our application will support only in IE browser but from 15th June onwards IE browser will not work so we have only option to use Edge in IE mode. Due to issue https://github.com/SeleniumHQ/selenium/issues/8868 selenium scripts are not working. It is a road blocker. Could you please provide resolution on priority before 15th June.

**Comment by p-system** [comment] 2022-06-07 07:27
Thank a lot for providing this fix for problem I have noticed. I am going to test all the cases in my app and I will post here if everything is now OK and issue can be close.

**Comment by diemol** [comment] 2022-06-09 07:06
@bwalderman is there a chance you could please help us to review https://github.com/SeleniumHQ/selenium/pull/10702?

**Comment by ven92** [comment] 2022-06-09 07:06
I'm facing the same issue. I tried with IE driver v4.0 & v4.2. MS Edge is getting launched in IE Mode, window handle works when only one Window present. But if multiple window gets open, then the code get stuck at driver.window_handles line. Could you please provide the fix ASAP..

**Comment by ven92** [comment] 2022-06-11 06:18
> Thank a lot for providing this fix for the problem I have noticed. I am going to test all the cases in my app and I will post here if everything is now OK and issue can be close.

Was fix provided for windows handles? Plz share the steps if you found any resolution

**Comment by p-system** [comment] 2022-06-15 10:53
Unfortunately I have upgraded  Selenium.WebDriver and Selenium.IEdriver (screen)  and run the same tests that made me create this error here on GitHub and the result is the same ( screens above are relevant ). The second window of tested application that is open via **window.open(url, name, winParms) function** is not detected by function **WindowHendlers**. 


![OCL_Handlers](https://user-images.githubusercontent.com/13451491/173806240-1fe3c446-ffaf-4950-9729-1e0de038dc6b.jpg)

**Comment by yusuke-noda** [comment] 2022-06-16 00:34
My pull request hasn't been merged yet, and the fixed IEDriver hasn't been released yet.
To test the fixed IEDriver, you need to build the IEDriver from source yourself.

**Comment by p-system** [comment] 2022-06-20 07:59
> My pull request hasn't been merged yet, and the fixed IEDriver hasn't been released yet. To test the fixed IEDriver, you need to build the IEDriver from source yourself.

Thanks a lot for this piece of information. Please let me know when those changes will be available as a NuGet packages. Recent updates in those packages mentioned (screen) above were in late May 2022 so I was convinced that the fixes were included there. If not please let me know when I can download new versions of libraries to my project and test it.

**Comment by 1merzoua** [comment] 2022-06-20 09:48
Hello @yusuke-noda, Same question as @p-system, any Idea when the fix will be available as NuGet packages ?
Thank you.

**Comment by titusfortner** [comment] 2022-06-23 04:27
Can someone from Microsoft (@ngaitonde or @bwalderman if you are available) do a once-over for the proposed solution by @yusuke-noda? I can't read C++ and it might be a bit before I have time to build a binary from the PR and run a test suite against it. If someone can double check the logic for us, we can get a release out with it. Thanks!

**Comment by bwalderman** [comment] 2022-06-24 21:47
@titusfortner I am planning to take a look early next week.

**Comment by 1merzoua** [comment] 2022-06-28 10:29
Any update about this issue ?

**Comment by 1merzoua** [comment] 2022-07-01 13:00
Hello @bwalderman, any update about this issue please ?

**Comment by p-system** [comment] 2022-07-08 15:27
Hi, is there any chance that this issue will be fix soon. I have posted this problem on 2 May and I have some serious problems with my testing projects concerning legacy applications running on IE / Edge. I would appreciate any information about progress on this issue. I have also posted  another issue "Problem with selecting OPTION element within a SELECT #26 " and there is no answer there as well.

**Comment by bwalderman** [comment] 2022-07-11 17:12
@p-system. I've approved the linked PR. The Edge team doesn't handle IEDriver releases, so I'd suggest reaching out to Selenium for questions about timeline.

**Comment by diemol** [comment] 2022-07-12 12:27
Thanks, @bwalderman. I will merge and coordinate with @titusfortner for a release.

**Comment by titusfortner** [comment] 2022-07-14 18:26
We just uploaded IEDriverServer 4.3, please let us know if it doesn't fix the problem — https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.3.0

**Comment by Ram22dot** [comment] 2022-08-25 14:40
@titusfortner In 4.3.0 version also not resolved to handle correct windows issue in edge browser. Seems it is fixed in 4.4.0 version. Please let us know when will release version 4.4.0.

* Fix bug to ensure correct window handle used by CDP (#10811)

**Comment by titusfortner** [comment] 2022-08-29 21:01
@Ram22dot all commits that have been merged into trunk for IEDriver are in v4.3

The code you are referencing is Java code for working with DevTools and is unrelated to Edge in IE Mode.

**Comment by p-system** [comment] 2022-10-26 09:55
I have tested all the windows in all legacy applications that are now run on Egde in IEMode. Now most of them are identify by a selenium test as a separate handler and can be navigated to without problem. Some of them unfortunately are not always identified and a number of handlers remains the same even if new window is open.  The situation is random. I run several times the same test and sometimes number of handlers is OK and sometimes it does not include new window that has been open by the test. Sometimes closing this new window and opening again during the test (in debug - break mode) makes the number of handlers update to correct number. 

I wait even 2 minutes and every several seconds get actual number of handlers just in case this whole process of getting a correct number of handlers is delayed but it does not help to get the right number. So the problem was improved but not solved completely. 

Please provide some clues how to overcome this problem.

var ieWindowHandlers = context.GetDriver().WindowHandles;

![obraz](https://user-images.githubusercontent.com/13451491/197995148-bc936271-0486-43d0-9f57-f150e02f5c94.png)

**Comment by jyosha3** [comment] 2022-11-23 18:26
Unable to handle windows with the latest versions of IE driver and selenium java versions.Any one was able to find a solution or workaround for the same.Can we please reopen this issue.

**Comment by bwalderman** [comment] 2022-11-29 20:17
@jyosha3 I've opened a new issue #59 since this appears to be a different root cause than the issue discussed here. Let's continue the conversation there.

**Closed by bwalderman** 2022-11-29 20:17 UTC
Labels: bug, tracked, ie
