### ISSUE TITLE
Running Selenium tests in EdgeInIE Mode on VM does not work unless the remote machine is connected.

### ISSUE THREAD

**Issue by MatsMats100** [MicrosoftEdge/EdgeWebDriver#27] opened 2022-06-08 05:02 UTC
We are trying to execute Selenium GUI Tests on Virtual Machines through Jenkin for the browser EdgeInIEMode. The Test runs without any issues when the remote machine is connected (and maximized)to our local laptop. However, the test execution halts after the browser is launched (but the URL is not loaded)if the machine is not connected or even if the remote machine is connected but minimized. Automation is getting started but doing nothing by displaying the below log all the time. It doesn't throw any error either. (When I connect back to the machine, I can see that the browser is launched but no more steps are performed beyond that.)

**Log output**
Writing to Selenium trace log: C:\LogRepo\Logs\Selenium.txt
Started InternetExplorerDriver server (32-bit)
4.0.0.0
Listening on port 45227
Only local connections are allowed

Please note: Same Tests can be executed in the same setup for other browsers without any issues even if the virtual machine/remote machine is disconnected/connected but minimized.

**Setup used**
Virtual machine Operating System: Win10
Selenium version: 3.141
Edge browser version: 103
IE Driver version: 4.0 (32-bit)

**The code used to launch EdgeInIE mode is**

System.setProperty("webdriver.ie.driver", "IE driver path");
InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
ops.put("ie.edgechromium", true);
ops.put("ie.edgepath", " C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe");
InternetExplorerDriver driver = new InternetExplorerDriver(edgeIe11Options);
driver.manage().window().maximize()
driver.get(http://www.google.com/);

With the above code, Tests are running without any issues in EdgeInIEMode on the local laptop.

**Comment by bwalderman** [comment] 2022-06-24 16:56
Thank you for reporting this. It sounds like it could be related to #15 which is already tracked on our internal backlog.

**Comment by MatsMats100** [comment] 2022-08-12 19:42
I have upgraded Selenium 4 but no luck either. (Please note: Tests are running fine on other browsers)

**Setup used**
Selenium 4.3.0  -  IE driver 4.2.0  -  Java SE 1.8


**Log output:**

Started InternetExplorerDriver server (32-bit)
4.0.0.0
Listening on port 50862
Only local connections are allowed
Step 1: Test Failed due to the below Exception.
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'RemoteMachineNo876', ip: '10.145.106.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: internet explorer, se:ieOptions: {ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr...}}], desiredCapabilities=Capabilities {browserName: internet explorer, ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., se:ieOptions: {ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr...}}}]
Capabilities {}

**Comment by bwalderman** [comment] 2022-12-14 18:33
Duplicate of #15. Both issues have the same root cause that there must be an interactive session.

**Closed by bwalderman** 2022-12-14 18:33 UTC
Labels: bug, tracked, ie
