### ISSUE TITLE
Selenium Edge IE Mode - Unable to create new session in Amazon workspaces. (Cloud Based Windows Machines)

### ISSUE THREAD

**Issue by message2guna** [MicrosoftEdge/EdgeWebDriver#32] opened 2022-06-16 12:56 UTC
Selenium Edge IE Mode - Unable to create new session in Amazon workspaces (Cloud Based Windows Machines). Same code is working fine in laptop.

Selenium : 4.0.0
Edge Version : 101
OS: Windows 10 (AWS Workspace)

**Code:**
System.setProperty("webdriver.ie.driver", properties.getProperty("InternetExplorerDriverPath"));
InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
edgeIe11Options.attachToEdgeChrome();
edgeIe11Options.withEdgeExecutablePath( "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
edgeIe11Options.introduceFlakinessByIgnoringSecurityDomains();
edgeIe11Options.destructivelyEnsureCleanSession();
edgeIe11Options.ignoreZoomSettings();
driver = new InternetExplorerDriver(edgeIe11Options);
break;

**Error:** 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Started InternetExplorerDriver server (32-bit)
4.0.0.0
Listening on port 65399
Only local connections are allowed
Exception in thread "pool-1-thread-1" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.3', revision: '7b1ebf28ef'

**Comment by bwalderman** [comment] 2022-06-24 17:01
Hi @message2guna. Can you try collecting more detailed log output from IEDriver? You can find info on how to configure this at https://www.selenium.dev/documentation/ie_driver_server/

**Comment by bwalderman** [comment] 2022-07-08 19:04
The error log in the issues description indicates that the session couldn't be created because the client is connecting from a remote address, but only local connections are allowed. Since this is expected behavior and there hasn't been any further activity, I'm going to close this issue.

**Closed by bwalderman** 2022-07-08 19:04 UTC
Labels: bug
