### ISSUE TITLE
unknown error: cannot determine loading status from unknown error: unexpected command response (Session info: MicrosoftEdge=103.0.1264.44)

### ISSUE THREAD

**Issue by prsnth04** [MicrosoftEdge/EdgeWebDriver#37] opened 2022-07-04 15:21 UTC
I am trying to run automation using edge driver with below 
Edge Version = 103.0.1264.44
Selenium.Support Version="4.3.0"
Selenium.WebDriver Version="4.3.0"

after running the script i am getting below error in various steps which was working. 

OpenQA.Selenium.WebDriverException: unknown error: cannot determine loading status
from unknown error: unexpected command response
(Session info: MicrosoftEdge=103.0.1264.44)
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.WebElement.Click()

**Comment by bwalderman** [comment] 2022-07-08 18:55
Thank you for reporting this. This is a duplicate of https://github.com/MicrosoftEdge/EdgeWebDriver/issues/21 which our team helped fix in Chrome and Edge 104. The ChromeDriver team has merged this fix into 103 and a new driver should be released very soon. You can follow the latest updates on this issue at: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121

The fix should be available in Edge WebDriver 103 within a few days after it is released for ChromeDriver 103.

**Closed by bwalderman** 2022-07-08 18:55 UTC
Labels: bug
